---
sudo: required

dist: bionic

env:
  - APP_NAME=terraform
  - APP_VERSION=0.12.6
  - APP_ARCH=linux_amd64
  - APP_URL=https://releases.hashicorp.com

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y unzip wget

script:
  - wget -v $APP_URL/$APP_NAME/$APP_VERSION/$APP_NAME_$APP_VERSION_$APP_ARCH.zip
  - unzip $APP_NAME$APP_VERSION$APP_ARCH.zip -d /usr/local/bin/
  - chmod +x /usr/local/bin/$APP_NAME
  - $APP_NAME --version
  - $APP_NAME init
  - $APP_NAME plan